site_name: Sweeper
repo_url: https://github.com/agrvz/sweeper

docs_dir: docs

theme:
  name: material
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - toc.follow
    - toc.integrate
  palette:
    scheme: slate
    primary: deep purple
    accent: orange
