[project]
name = "sweeper"
version = "0.1.0"
description = "CLI for creating sweepstakes"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.uv]
package = false
dev-dependencies = [
  "pytest",
  "pytest-clarity",
  "ruff"
]
