name: lint

on:
  pull_request:
    types: [ready_for_review]
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint with ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint with ruff
        # v3
        uses: astral-sh/ruff-action@0c50076f12c38c3d0115b7b519b54a91cb9cf0ad
        with:
          version: "v0.12.4"
          args: "format --check --diff"
